version: '3'
services:
  web:
    build: .
    ports:
      - "5000:3000"
  db:
    image: "mysql"
    restart: always
    environment:
      MYSQL_DATABASE: 'test_finance'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-data:/foo

volumes:
  db-data: